#!/usr/bin/env python
# -*- coding: utf-8 -*-
from project_repo.weather_api import main
import sys

try:
    while True:
        main()
except KeyboardInterrupt:
    print('\nGoodbye!')
    sys.exit(0)
